project_name: status-client
before:
  hooks:
    - go mod tidy
builds:
  - id: default-build
    main: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - windows
    goarch:
      - arm
      - arm64
      - '386'
      - amd64
      - mips
      - mipsle

  - id: darwin-amd64-build
    main: ./cmd/client
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64

  - id: darwin-arm64-build
    main: ./cmd/client
    env:
      - CGO_ENABLED=1
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
